// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"goboot/cmd/migrate/conf"
	"goboot/internal/config"
	"goboot/internal/migration"
	"goboot/internal/repository/repo"
)

// Injectors from wire.go:

func newApp() (*migration.Migrate, func(), error) {
	migrateConf := ConfProvider()
	wdb := repo.NewWDB(migrateConf)
	logger := LoggerProvider(migrateConf)
	migrate := migration.NewMigrate(wdb, logger)
	return migrate, func() {
	}, nil
}

// wire.go:

var confSet = wire.NewSet(ConfProvider, LoggerProvider, wire.Bind(new(config.Conf), new(*conf.MigrateConf)))

var repoSet = wire.NewSet(repo.NewWDB, repo.NewRepository)

var migrateSet = wire.NewSet(migration.NewMigrate)
